#!/usr/bin/env python3

import os
import pathlib
import subprocess
import click

SNAP = pathlib.Path(os.getenv("SNAP") or "/snap/microk8s/current")
HELM = SNAP / "microk8s-helm3.wrapper"

@click.command()
def main():
    click.echo("Disabling AMD GPU operator")
    subprocess.check_output([HELM, "uninstall", "amd-gpu-operator", "-n", "kube-amd-gpu"])

if __name__ == "__main__":
    main()
    

