#!/usr/bin/env python3

import os
import pathlib
import subprocess
import click

SNAP = pathlib.Path(os.getenv("SNAP") or "/snap/microk8s/current")
HELM = SNAP / "microk8s-helm3.wrapper"

@click.command()
#@click.Option("--debug-disable", is_flag=True)
def main(debug_disable=False):
    click.echo("Disabling AMD GPU operator")
    uninstall_args = ["uninstall", "amd-gpu-operator", "-n", "kube-amd-gpu"]

    if debug_disable:
        uninstall_args.append("--debug")

    subprocess.check_output([HELM, *uninstall_args])

if __name__ == "__main__":
    main()
    

